# Generated by Django 3.0 on 2019-12-02 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191202_2038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
